# Generated by Django 5.0.1 on 2024-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cphonenumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(choices=[('Margherita', 'Margherita'), ('Pepperoni', 'Pepperoni'), ('Hawaiian', 'Hawaiian'), ('Meat Lovers', 'Meat Lovers'), ('Veggie Supreme', 'Veggie Supreme'), ('BBQ Chicken', 'BBQ Chicken'), ('Four Cheese', 'Four Cheese'), ('Supreme', 'Supreme'), ('Mushroom', 'Mushroom'), ('Sausage and Mushroom', 'Sausage and Mushroom')], max_length=100)),
                ('psize', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large'), ('Personal', 'Personal'), ('Family Size', 'Family Size'), ('Party Size', 'Party Size'), ('Jumbo', 'Jumbo'), ('Extra Small', 'Extra Small'), ('Giant', 'Giant')], max_length=50)),
                ('pnumber', models.IntegerField()),
                ('pdrinks', models.CharField(choices=[('Pepsi', 'Pepsi'), ('7up', '7up'), ('Water', 'Water'), ('Merinda', 'Merinda')], max_length=100)),
            ],
        ),
    ]
