# Generated by Django 5.0.1 on 2024-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbyorder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='pizza',
            name='cname',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='cphonenumber',
            field=models.CharField(default='9876543210', max_length=20),
        ),
    ]
